# Generated by Django 2.0.6 on 2018-06-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_upc', models.CharField(default='not given', max_length=20)),
                ('product_name', models.CharField(max_length=30)),
                ('product_stock', models.IntegerField(default=0)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
