# Generated by Django 2.0.6 on 2018-06-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='not given', max_length=20)),
                ('store_code', models.IntegerField(default=0)),
            ],
        ),
    ]
